services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped

  backend:
    build:
      context: ./server 
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped
